services:
  dicebear:
    image: dicebear/api:4
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      OPTIONS: "1"
      LOGGER: "0"
      WORKERS: "2"
      CACHE_CONTROL_AVATARS: "31536000"
      CACHE_CONTROL_STYLES: "3600"
    tmpfs:
      - /run
      - /tmp
