-- Rede Lua LuaCore: replaces external search/recommendation/analytics services
-- with first-party Supabase/Postgres capabilities and adds three learning systems.

-- 1) Native search index -----------------------------------------------------
alter table public.rede_lua_activities
  add column if not exists search_vector tsvector;

create or replace function public.rede_lua_refresh_activity_search_vector()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.search_vector := to_tsvector(
    'portuguese'::regconfig,
    coalesce(new.title,'') || ' ' || coalesce(new.subject,'') || ' ' ||
    coalesce(new.description,'') || ' ' || coalesce(array_to_string(new.tags,' '),'')
  );
  return new;
end;
$$;

update public.rede_lua_activities
set search_vector = to_tsvector(
  'portuguese'::regconfig,
  coalesce(title,'') || ' ' || coalesce(subject,'') || ' ' ||
  coalesce(description,'') || ' ' || coalesce(array_to_string(tags,' '),'')
)
where search_vector is null;

drop trigger if exists rede_lua_activity_search_vector_trg on public.rede_lua_activities;
create trigger rede_lua_activity_search_vector_trg
before insert or update of title,subject,description,tags on public.rede_lua_activities
for each row execute function public.rede_lua_refresh_activity_search_vector();

create index if not exists rede_lua_activities_search_vector_idx
  on public.rede_lua_activities using gin (search_vector);
create index if not exists rede_lua_activities_title_trgm_idx
  on public.rede_lua_activities using gin (lower(title) extensions.gin_trgm_ops);
create index if not exists rede_lua_activities_subject_trgm_idx
  on public.rede_lua_activities using gin (lower(subject) extensions.gin_trgm_ops);

-- 2) First-party privacy analytics -----------------------------------------
create table if not exists public.rede_lua_core_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  session_id uuid not null,
  event_name text not null check (event_name ~ '^[a-z0-9_.:-]{2,64}$'),
  surface text not null check (char_length(surface) between 2 and 64),
  activity_id uuid null references public.rede_lua_activities(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object' and octet_length(metadata::text) <= 4096),
  created_at timestamptz not null default now()
);

create index if not exists rede_lua_core_events_time_idx on public.rede_lua_core_events(created_at desc);
create index if not exists rede_lua_core_events_activity_idx on public.rede_lua_core_events(activity_id, created_at desc) where activity_id is not null;
create index if not exists rede_lua_core_events_user_idx on public.rede_lua_core_events(user_id, created_at desc) where user_id is not null;

alter table public.rede_lua_core_events enable row level security;

drop policy if exists rede_lua_core_events_anon_insert on public.rede_lua_core_events;
create policy rede_lua_core_events_anon_insert on public.rede_lua_core_events
  for insert to anon
  with check (user_id is null);

drop policy if exists rede_lua_core_events_auth_insert on public.rede_lua_core_events;
create policy rede_lua_core_events_auth_insert on public.rede_lua_core_events
  for insert to authenticated
  with check (user_id = (select auth.uid()));

revoke all on public.rede_lua_core_events from anon, authenticated;
grant insert on public.rede_lua_core_events to anon, authenticated;
grant usage, select on sequence public.rede_lua_core_events_id_seq to anon, authenticated;

create or replace function public.rede_lua_track_core_event(
  p_session_id uuid,
  p_event_name text,
  p_surface text,
  p_activity_id uuid default null,
  p_metadata jsonb default '{}'::jsonb
) returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_session_id is null then raise exception 'INVALID_SESSION'; end if;
  if p_event_name !~ '^[a-z0-9_.:-]{2,64}$' then raise exception 'INVALID_EVENT'; end if;
  if char_length(coalesce(p_surface,'')) not between 2 and 64 then raise exception 'INVALID_SURFACE'; end if;
  insert into public.rede_lua_core_events(user_id, session_id, event_name, surface, activity_id, metadata)
  values ((select auth.uid()), p_session_id, p_event_name, left(p_surface,64), p_activity_id, coalesce(p_metadata,'{}'::jsonb));
end;
$$;

grant execute on function public.rede_lua_track_core_event(uuid,text,text,uuid,jsonb) to anon, authenticated;

-- 3) Native search + recommendation engine ---------------------------------
create or replace function public.rede_lua_search_activities(p_query text, p_limit integer default 12)
returns table (
  id uuid,
  title text,
  subject text,
  description text,
  difficulty text,
  tags text[],
  status text,
  question_count bigint,
  created_at timestamptz,
  updated_at timestamptz,
  score double precision
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  with input as (
    select trim(coalesce(p_query,'')) as raw,
           websearch_to_tsquery('portuguese'::regconfig, trim(coalesce(p_query,''))) as tsq
  )
  select a.id, a.title, a.subject, a.description, a.difficulty, a.tags, a.status,
         (select count(*) from public.rede_lua_questions q where q.activity_id = a.id) as question_count,
         a.created_at, a.updated_at,
         (
           ts_rank_cd(a.search_vector, input.tsq)::double precision * 4.0
           + extensions.similarity(lower(a.title), lower(input.raw)) * 2.4
           + extensions.similarity(lower(a.subject), lower(input.raw)) * 1.6
           + case when lower(a.title) like '%' || lower(input.raw) || '%' then 1.2 else 0 end
           + case when lower(a.subject) like '%' || lower(input.raw) || '%' then 0.8 else 0 end
           + case when exists (select 1 from unnest(a.tags) t where lower(t) like '%' || lower(input.raw) || '%') then 0.9 else 0 end
         ) as score
  from public.rede_lua_activities a
  cross join input
  where a.status = 'published'
    and char_length(input.raw) between 2 and 90
    and (
      a.search_vector @@ input.tsq
      or extensions.similarity(lower(a.title), lower(input.raw)) > 0.12
      or extensions.similarity(lower(a.subject), lower(input.raw)) > 0.18
      or lower(a.title) like '%' || lower(input.raw) || '%'
      or lower(a.subject) like '%' || lower(input.raw) || '%'
      or lower(a.description) like '%' || lower(input.raw) || '%'
      or exists (select 1 from unnest(a.tags) t where lower(t) like '%' || lower(input.raw) || '%')
    )
  order by score desc, a.updated_at desc
  limit greatest(1, least(coalesce(p_limit,12), 30));
$$;

grant execute on function public.rede_lua_search_activities(text,integer) to anon, authenticated;

-- Recommendation function is defined after mastery storage is created.

-- 4) Teacher System #1: Forja Lunar ----------------------------------------
create table if not exists public.rede_lua_question_bank (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (char_length(subject) between 2 and 50),
  skill_key text not null default 'geral' check (char_length(skill_key) between 2 and 80),
  prompt text not null check (char_length(prompt) between 3 and 700),
  choices jsonb not null check (jsonb_typeof(choices) = 'array' and jsonb_array_length(choices) between 2 and 5),
  correct_index integer not null check (correct_index >= 0 and correct_index < jsonb_array_length(choices)),
  explanation text not null default '',
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  tags text[] not null default '{}',
  times_used integer not null default 0 check (times_used >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists rede_lua_question_bank_owner_subject_idx on public.rede_lua_question_bank(owner_id, subject, updated_at desc);
create index if not exists rede_lua_question_bank_prompt_trgm_idx on public.rede_lua_question_bank using gin (lower(prompt) extensions.gin_trgm_ops);

alter table public.rede_lua_question_bank enable row level security;

drop policy if exists rede_lua_question_bank_owner_all on public.rede_lua_question_bank;
create policy rede_lua_question_bank_owner_all on public.rede_lua_question_bank
  for all to authenticated
  using (owner_id = (select auth.uid()) and (select public.rede_lua_is_teacher()))
  with check (owner_id = (select auth.uid()) and (select public.rede_lua_is_teacher()));

grant select, insert, update, delete on public.rede_lua_question_bank to authenticated;

create or replace function public.rede_lua_forge_questions(p_subject text default null, p_limit integer default 30)
returns table (
  id uuid, subject text, skill_key text, prompt text, choices jsonb,
  correct_index integer, explanation text, difficulty text, tags text[], times_used integer, updated_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select q.id, q.subject, q.skill_key, q.prompt, q.choices, q.correct_index, q.explanation,
         q.difficulty, q.tags, q.times_used, q.updated_at
  from public.rede_lua_question_bank q
  where q.owner_id = (select auth.uid())
    and (p_subject is null or trim(p_subject) = '' or lower(q.subject) = lower(trim(p_subject)))
  order by q.times_used desc, q.updated_at desc
  limit greatest(1, least(coalesce(p_limit,30), 100));
$$;

grant execute on function public.rede_lua_forge_questions(text,integer) to authenticated;

create or replace function public.rede_lua_save_forge_question(
  p_subject text,
  p_skill_key text,
  p_prompt text,
  p_choices jsonb,
  p_correct_index integer,
  p_explanation text default '',
  p_difficulty text default 'medium',
  p_tags text[] default '{}'
) returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare v_id uuid;
begin
  if not public.rede_lua_is_teacher() then raise exception 'TEACHER_REQUIRED'; end if;
  if jsonb_typeof(p_choices) <> 'array' or jsonb_array_length(p_choices) not between 2 and 5 then raise exception 'INVALID_CHOICES'; end if;
  if p_correct_index < 0 or p_correct_index >= jsonb_array_length(p_choices) then raise exception 'INVALID_CORRECT_INDEX'; end if;
  insert into public.rede_lua_question_bank(owner_id,subject,skill_key,prompt,choices,correct_index,explanation,difficulty,tags)
  values((select auth.uid()), trim(p_subject), coalesce(nullif(trim(p_skill_key),''),'geral'), trim(p_prompt), p_choices,
         p_correct_index, left(coalesce(p_explanation,''),900), p_difficulty, coalesce(p_tags,'{}'))
  returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.rede_lua_save_forge_question(text,text,text,jsonb,integer,text,text,text[]) to authenticated;

-- 5) Learning mastery core --------------------------------------------------
create table if not exists public.rede_lua_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  attempts integer not null default 0,
  correct_count integer not null default 0,
  mastery_score numeric(5,4) not null default 0.5000 check (mastery_score between 0 and 1),
  confidence numeric(5,4) not null default 0.0000 check (confidence between 0 and 1),
  last_result boolean null,
  updated_at timestamptz not null default now(),
  primary key(user_id, subject)
);

create index if not exists rede_lua_mastery_user_score_idx on public.rede_lua_mastery(user_id, mastery_score, updated_at desc);
alter table public.rede_lua_mastery enable row level security;

drop policy if exists rede_lua_mastery_own_read on public.rede_lua_mastery;
create policy rede_lua_mastery_own_read on public.rede_lua_mastery
  for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists rede_lua_mastery_teacher_read on public.rede_lua_mastery;
create policy rede_lua_mastery_teacher_read on public.rede_lua_mastery
  for select to authenticated
  using (
    (select public.rede_lua_is_teacher())
    and exists (
      select 1
      from public.rede_lua_participants p
      join public.rede_lua_games g on g.id=p.game_id
      where p.user_id=rede_lua_mastery.user_id and g.host_id=(select auth.uid())
    )
  );

grant select on public.rede_lua_mastery to authenticated;

alter table public.rede_lua_profiles add column if not exists last_learning_date date null;

-- Students may read their own participation/answers. This powers Constelação.
drop policy if exists rede_lua_participants_own_read on public.rede_lua_participants;
create policy rede_lua_participants_own_read on public.rede_lua_participants
  for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists rede_lua_answers_own_read on public.rede_lua_answers;
create policy rede_lua_answers_own_read on public.rede_lua_answers
  for select to authenticated
  using (exists (
    select 1 from public.rede_lua_participants p
    where p.id = rede_lua_answers.participant_id and p.user_id = (select auth.uid())
  ));

create or replace function public.rede_lua_after_answer_learning()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid;
  v_subject text;
  v_xp integer;
begin
  select p.user_id, a.subject
    into v_user, v_subject
  from public.rede_lua_participants p
  join public.rede_lua_games g on g.id = new.game_id
  join public.rede_lua_activities a on a.id = g.activity_id
  where p.id = new.participant_id;

  if v_user is null or v_subject is null then return new; end if;

  insert into public.rede_lua_mastery(user_id,subject,attempts,correct_count,mastery_score,confidence,last_result,updated_at)
  values(
    v_user,
    v_subject,
    1,
    case when new.correct then 1 else 0 end,
    case when new.correct then 0.5800 else 0.4200 end,
    0.2500,
    new.correct,
    now()
  )
  on conflict(user_id,subject) do update set
    attempts = public.rede_lua_mastery.attempts + 1,
    correct_count = public.rede_lua_mastery.correct_count + case when new.correct then 1 else 0 end,
    mastery_score = round(greatest(0.0500, least(0.9800,
      public.rede_lua_mastery.mastery_score * 0.84 + (case when new.correct then 1.0 else 0.0 end) * 0.16
    ))::numeric,4),
    confidence = round(least(0.9900, 1.0 - (1.0 / (1.0 + ((public.rede_lua_mastery.attempts + 1)::numeric / 3.0))))::numeric,4),
    last_result = new.correct,
    updated_at = now();

  insert into public.rede_lua_subject_affinity(user_id,subject,score)
  values(v_user,v_subject,case when new.correct then 4 else 1 end)
  on conflict(user_id,subject) do update set score=public.rede_lua_subject_affinity.score+excluded.score,updated_at=now();

  v_xp := case when new.correct then greatest(18, least(85, 18 + (new.awarded_points / 5))) else 5 end;
  update public.rede_lua_profiles
  set
    xp = xp + v_xp,
    level = greatest(level, 1 + floor((xp + v_xp)::numeric / 500)::integer),
    streak_days = case
      when last_learning_date = current_date then streak_days
      when last_learning_date = current_date - 1 then streak_days + 1
      else 1
    end,
    last_learning_date = current_date,
    updated_at = now()
  where user_id = v_user;

  return new;
end;
$$;

revoke all on function public.rede_lua_after_answer_learning() from public, anon, authenticated;

drop trigger if exists rede_lua_after_answer_learning_trg on public.rede_lua_answers;
create trigger rede_lua_after_answer_learning_trg
after insert on public.rede_lua_answers
for each row execute function public.rede_lua_after_answer_learning();

create or replace function public.rede_lua_recommend_activities(p_limit integer default 8)
returns table (
  id uuid,
  title text,
  subject text,
  description text,
  difficulty text,
  tags text[],
  status text,
  question_count bigint,
  created_at timestamptz,
  updated_at timestamptz,
  score double precision
)
language sql
stable
security invoker
set search_path = public
as $$
  select a.id, a.title, a.subject, a.description, a.difficulty, a.tags, a.status,
         (select count(*) from public.rede_lua_questions q where q.activity_id = a.id) as question_count,
         a.created_at, a.updated_at,
         (
           coalesce(least(3.0, ln(1 + af.score::double precision)), 0.0)
           + coalesce((1.0 - m.mastery_score::double precision) * 2.2, 0.45)
           + case
               when m.mastery_score >= 0.78 and a.difficulty = 'hard' then 1.0
               when m.mastery_score between 0.42 and 0.78 and a.difficulty = 'medium' then 0.8
               when (m.mastery_score is null or m.mastery_score < 0.42) and a.difficulty = 'easy' then 0.7
               else 0.15
             end
           + greatest(0.0, 1.0 - extract(epoch from (now() - a.updated_at)) / 2592000.0) * 0.35
         ) as score
  from public.rede_lua_activities a
  left join public.rede_lua_subject_affinity af
    on af.user_id = (select auth.uid()) and lower(af.subject) = lower(a.subject)
  left join public.rede_lua_mastery m
    on m.user_id = (select auth.uid()) and lower(m.subject) = lower(a.subject)
  where a.status = 'published'
  order by score desc, a.updated_at desc
  limit greatest(1, least(coalesce(p_limit,8), 20));
$$;

grant execute on function public.rede_lua_recommend_activities(integer) to anon, authenticated;

-- 6) Teacher System #2: Radar de Aprendizagem -------------------------------
create or replace function public.rede_lua_teacher_radar(p_days integer default 30)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with
  cfg as (select greatest(1,least(coalesce(p_days,30),180)) as days),
  teacher_games as (
    select g.id, g.activity_id, g.code, g.status, g.created_at, g.ended_at, a.title, a.subject
    from public.rede_lua_games g
    join public.rede_lua_activities a on a.id=g.activity_id
    cross join cfg
    where g.host_id=(select auth.uid()) and g.created_at >= now() - make_interval(days => cfg.days)
  ),
  ans as (
    select an.*, p.user_id, p.display_name, tg.title as activity_title, tg.subject
    from public.rede_lua_answers an
    join public.rede_lua_participants p on p.id=an.participant_id
    join teacher_games tg on tg.id=an.game_id
  ),
  hotspots as (
    select q.id as question_id, left(q.prompt,220) as prompt, tg.title as activity_title, tg.subject,
           count(an.id)::int as total_answers,
           count(an.id) filter (where an.correct=false)::int as wrong_answers,
           case when count(an.id)=0 then 0 else round((count(an.id) filter (where an.correct=false)::numeric / count(an.id)::numeric)*100,1) end as error_rate
    from teacher_games tg
    join public.rede_lua_questions q on q.activity_id=tg.activity_id
    left join public.rede_lua_answers an on an.game_id=tg.id and an.question_id=q.id
    group by q.id,q.prompt,tg.title,tg.subject
    having count(an.id) > 0
    order by error_rate desc, total_answers desc
    limit 8
  ),
  learner_subjects as (
    select distinct a.user_id, a.display_name, a.subject
    from ans a where a.user_id is not null
  ),
  learners as (
    select ls.user_id, max(ls.display_name) as display_name, ls.subject,
           m.mastery_score, m.confidence, m.attempts,
           case when m.mastery_score < 0.42 then 'intervir' when m.mastery_score < 0.68 then 'acompanhar' else 'fluente' end as signal
    from learner_subjects ls
    join public.rede_lua_mastery m on m.user_id=ls.user_id and lower(m.subject)=lower(ls.subject)
    group by ls.user_id,ls.subject,m.mastery_score,m.confidence,m.attempts
    order by m.mastery_score asc, m.confidence desc
    limit 24
  )
select jsonb_build_object(
  'summary', jsonb_build_object(
    'games', (select count(*) from teacher_games),
    'participants', (select count(distinct participant_id) from ans),
    'answers', (select count(*) from ans),
    'accuracy', (select coalesce(round((count(*) filter (where correct)::numeric / nullif(count(*),0))*100,1),0) from ans)
  ),
  'hotspots', coalesce((select jsonb_agg(to_jsonb(h)) from hotspots h),'[]'::jsonb),
  'learners', coalesce((select jsonb_agg(to_jsonb(l)) from learners l),'[]'::jsonb),
  'recentGames', coalesce((select jsonb_agg(to_jsonb(x)) from (
    select id,code,status,title,subject,created_at,ended_at from teacher_games order by created_at desc limit 8
  ) x),'[]'::jsonb)
)
where public.rede_lua_is_teacher();
$$;

grant execute on function public.rede_lua_teacher_radar(integer) to authenticated;

-- 7) Student System: Constelação --------------------------------------------
create or replace function public.rede_lua_student_constellation()
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with
  me as (
    select p.user_id,p.display_name,p.xp,p.level,p.streak_days
    from public.rede_lua_profiles p
    where p.user_id=(select auth.uid())
  ),
  mastery as (
    select m.subject,m.mastery_score,m.confidence,m.attempts,m.correct_count,m.last_result,m.updated_at
    from public.rede_lua_mastery m
    where m.user_id=(select auth.uid())
    order by m.mastery_score asc, m.updated_at desc
  ),
  today as (
    select a.id,a.correct,g.activity_id,act.subject,act.difficulty
    from public.rede_lua_answers a
    join public.rede_lua_participants p on p.id=a.participant_id
    join public.rede_lua_games g on g.id=a.game_id
    join public.rede_lua_activities act on act.id=g.activity_id
    where p.user_id=(select auth.uid()) and a.answered_at >= current_date
  ),
  weak_subject as (
    select subject from mastery order by mastery_score asc, confidence desc limit 1
  ),
  strong_subject as (
    select subject from mastery order by mastery_score desc, confidence desc limit 1
  ),
  recover_activity as (
    select a.id,a.title,a.subject,a.description,a.difficulty
    from public.rede_lua_activities a
    where a.status='published'
      and lower(a.subject)=lower(coalesce((select subject from weak_subject),a.subject))
    order by case a.difficulty when 'easy' then 0 when 'medium' then 1 else 2 end, a.updated_at desc
    limit 1
  ),
  explore_activity as (
    select a.id,a.title,a.subject,a.description,a.difficulty
    from public.rede_lua_activities a
    where a.status='published'
      and not exists (select 1 from mastery m where lower(m.subject)=lower(a.subject))
    order by md5(coalesce((select auth.uid())::text,'anon') || current_date::text || a.id::text)
    limit 1
  ),
  challenge_activity as (
    select a.id,a.title,a.subject,a.description,a.difficulty
    from public.rede_lua_activities a
    where a.status='published'
      and (not exists(select 1 from strong_subject) or lower(a.subject)=lower((select subject from strong_subject)))
    order by case a.difficulty when 'hard' then 0 when 'medium' then 1 else 2 end, a.updated_at desc
    limit 1
  ),
  missions as (
    select 'recuperar'::text as type, 'Fortaleça um ponto fraco'::text as label,
           r.id as activity_id,r.title,r.subject,r.description,r.difficulty,
           3::int as target,
           least(3,(select count(*)::int from today t where lower(t.subject)=lower(r.subject))) as progress,
           90::int as reward_xp
    from recover_activity r
    union all
    select 'explorar','Descubra uma nova matéria',e.id,e.title,e.subject,e.description,e.difficulty,
           2, least(2,(select count(*)::int from today t where lower(t.subject)=lower(e.subject))),70
    from explore_activity e
    union all
    select 'desafio','Teste o que você domina',c.id,c.title,c.subject,c.description,c.difficulty,
           4, least(4,(select count(*)::int from today t where lower(t.subject)=lower(c.subject))),120
    from challenge_activity c
  )
select jsonb_build_object(
  'profile', coalesce((select to_jsonb(me) from me),'{}'::jsonb),
  'mastery', coalesce((select jsonb_agg(to_jsonb(m)) from mastery m),'[]'::jsonb),
  'missions', coalesce((select jsonb_agg(to_jsonb(ms)) from missions ms),'[]'::jsonb),
  'today', jsonb_build_object(
    'answers',(select count(*) from today),
    'correct',(select count(*) from today where correct),
    'accuracy',(select coalesce(round((count(*) filter (where correct)::numeric / nullif(count(*),0))*100,1),0) from today)
  )
)
where (select auth.uid()) is not null;
$$;

grant execute on function public.rede_lua_student_constellation() to authenticated;

-- Small performance indexes for the new dashboards.
create index if not exists rede_lua_answers_participant_answered_idx on public.rede_lua_answers(participant_id, answered_at desc);
create index if not exists rede_lua_answers_game_correct_idx on public.rede_lua_answers(game_id, correct);
create index if not exists rede_lua_participants_user_game_idx on public.rede_lua_participants(user_id, game_id) where user_id is not null;
